/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prundustechnologies.View;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nipuni
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        mythread1 t = new mythread1();
        t.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        appointmentButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        paymentButton = new javax.swing.JButton();
        productButton = new javax.swing.JButton();
        serviceButton = new javax.swing.JButton();
        clientButton = new javax.swing.JButton();
        reportButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        lgDate = new javax.swing.JLabel();
        stringDay = new javax.swing.JLabel();
        lgTime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jdp = new javax.swing.JDesktopPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(2657, 741));

        jLabel4.setText("jLabel2");

        jPanel6.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hello User");
        jPanel6.add(jLabel1);
        jLabel1.setBounds(0, 0, 230, 140);

        appointmentButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        appointmentButton.setForeground(new java.awt.Color(35, 68, 179));
        appointmentButton.setText("Appointment");
        appointmentButton.setToolTipText("Add New,Search,Delete & Make Changes In Appointments");
        appointmentButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        appointmentButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appointmentButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        appointmentButton.setIconTextGap(10);
        appointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentButtonActionPerformed(evt);
            }
        });
        jPanel6.add(appointmentButton);
        appointmentButton.setBounds(10, 200, 210, 50);

        orderButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        orderButton.setForeground(new java.awt.Color(35, 68, 179));
        orderButton.setText("Order");
        orderButton.setToolTipText("Add New Orders(Cake Order,Sewing Order,Treatements,Wedding Arrangements)");
        orderButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        orderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orderButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        orderButton.setIconTextGap(15);
        orderButton.setPreferredSize(new java.awt.Dimension(209, 62));
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });
        jPanel6.add(orderButton);
        orderButton.setBounds(10, 270, 209, 50);

        paymentButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        paymentButton.setForeground(new java.awt.Color(35, 68, 179));
        paymentButton.setText("Payment");
        paymentButton.setToolTipText("Add Payments");
        paymentButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        paymentButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        paymentButton.setIconTextGap(20);
        paymentButton.setPreferredSize(new java.awt.Dimension(209, 62));
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });
        jPanel6.add(paymentButton);
        paymentButton.setBounds(10, 340, 209, 50);

        productButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        productButton.setForeground(new java.awt.Color(35, 68, 179));
        productButton.setText("Product");
        productButton.setToolTipText("Add New,Search,Delete Product & Make Changes In Stock");
        productButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        productButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productButton.setIconTextGap(13);
        productButton.setPreferredSize(new java.awt.Dimension(209, 62));
        productButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productButtonActionPerformed(evt);
            }
        });
        jPanel6.add(productButton);
        productButton.setBounds(10, 410, 209, 50);

        serviceButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        serviceButton.setForeground(new java.awt.Color(35, 68, 179));
        serviceButton.setText("Service");
        serviceButton.setToolTipText("Add New");
        serviceButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        serviceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        serviceButton.setIconTextGap(25);
        serviceButton.setPreferredSize(new java.awt.Dimension(209, 62));
        serviceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceButtonActionPerformed(evt);
            }
        });
        jPanel6.add(serviceButton);
        serviceButton.setBounds(10, 480, 209, 50);

        clientButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        clientButton.setForeground(new java.awt.Color(35, 68, 179));
        clientButton.setText("Client");
        clientButton.setToolTipText("Add New ,Search,Delete Client & Make Changes In Client Details");
        clientButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        clientButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        clientButton.setIconTextGap(25);
        clientButton.setPreferredSize(new java.awt.Dimension(209, 62));
        clientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientButtonActionPerformed(evt);
            }
        });
        jPanel6.add(clientButton);
        clientButton.setBounds(10, 550, 209, 50);

        reportButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        reportButton.setForeground(new java.awt.Color(35, 68, 179));
        reportButton.setText("Others");
        reportButton.setToolTipText("Important Reports About Business\n\n\n");
        reportButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        reportButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        reportButton.setIconTextGap(25);
        reportButton.setPreferredSize(new java.awt.Dimension(209, 62));
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });
        jPanel6.add(reportButton);
        reportButton.setBounds(10, 620, 209, 50);

        jLabel5.setText("jLabel5");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(0, 0, 240, 720);

        jPanel2.setLayout(null);

        logoutButton.setBackground(new java.awt.Color(0, 153, 255));
        logoutButton.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log Out");
        logoutButton.setToolTipText("Log Out from the Session");
        logoutButton.setAutoscrolls(true);
        logoutButton.setBorder(null);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.setIconTextGap(6);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel2.add(logoutButton);
        logoutButton.setBounds(970, 20, 150, 40);

        lgDate.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lgDate.setText("jLabel4");
        jPanel2.add(lgDate);
        lgDate.setBounds(700, 100, 120, 18);

        stringDay.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        stringDay.setText("Date");
        jPanel2.add(stringDay);
        stringDay.setBounds(820, 100, 60, 18);

        lgTime.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lgTime.setText("jLabel4");
        jPanel2.add(lgTime);
        lgTime.setBounds(910, 100, 110, 18);

        jLabel3.setBackground(new java.awt.Color(0, 153, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prundustechnologies/Images/logo_2.png"))); // NOI18N
        jLabel3.setText("Prundus Technologies");
        jLabel3.setAlignmentX(1.0F);
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 690, 140);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(690, 0, 510, 140);

        jdp.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel8.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 1, 1));
        jLabel8.setText("We Discover Your True Beauty...");
        jdp.add(jLabel8);
        jLabel8.setBounds(420, 500, 750, 60);

        jLabel7.setFont(new java.awt.Font("Cambria", 3, 70)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Welcome To C & C Beauty Salon...");
        jdp.add(jLabel7);
        jLabel7.setBounds(70, 30, 1110, 80);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdp, javax.swing.GroupLayout.PREFERRED_SIZE, 2415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jdp))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

         public class mythread1 extends Thread{
    
        public void run(){
        
            while(true){

                
            setDate();
            
               
            try {
                
                this.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }}
    
    }
         
         private void setDate(){
       // SimpleDateFormat dte = new SimpleDateFormat("YYY-MM-dd",Locale.getDefault());
       // lg_date.setText(dte);
        
        SimpleDateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat timeFormatter = new SimpleDateFormat("HH:mm:ss");
        java.util.Date today = Calendar.getInstance().getTime();
        String dateAsString = dateFormatter.format(today);
        String timeAsString = timeFormatter.format(today);
        lgTime.setText(timeAsString);
        lgDate.setText(dateAsString);
        
        java.util.Date now = new java.util.Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEEEEEEE", Locale.US); 
        String asWeek = dateFormat.format(now);
        stringDay.setText(asWeek);
        //lg_date.setText(dateAsString);
    }   
    
    private void appointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentButtonActionPerformed

    }//GEN-LAST:event_appointmentButtonActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed

    }//GEN-LAST:event_orderButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed

    }//GEN-LAST:event_paymentButtonActionPerformed

    private void productButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productButtonActionPerformed

    }//GEN-LAST:event_productButtonActionPerformed

    private void serviceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceButtonActionPerformed

    }//GEN-LAST:event_serviceButtonActionPerformed

    private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed

    }//GEN-LAST:event_clientButtonActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed

    }//GEN-LAST:event_reportButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed

    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointmentButton;
    private javax.swing.JButton clientButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JDesktopPane jdp;
    private javax.swing.JLabel lgDate;
    private javax.swing.JLabel lgTime;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton paymentButton;
    private javax.swing.JButton productButton;
    private javax.swing.JButton reportButton;
    private javax.swing.JButton serviceButton;
    private javax.swing.JLabel stringDay;
    // End of variables declaration//GEN-END:variables
}
